name: Buffer Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  sample_check:
    name: sample check
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'develop')
    steps:
      - name: welcoming to develop branch
        run : |
          echo "thanks for sending pull request to develop branch" 
          echo ${{ github.ref_name }}
  build_test:
    name: Build and execute the test binary
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'main')
    steps:
      - name: Checkout my code
        uses: actions/checkout@v2.3.4
      - name: Build the test binary
        run: |
          make build_test
          echo "#### Build test step completed  !!!!!!"
      - name: Execute the testcases
        run: |
          make execute_test
          echo "#### Executing the test cases completed  !!!!!!"
  release:
    name: Release the test binary in zip file format
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout my code
        uses: actions/checkout@v2.3.4
      - name: Install the needed utils
        run: |
          sudo apt-get install zip
          sudo apt-get install build-essential
      - name: Build the test binary
        run: |
          make build_test
          echo "#### Build test step completed  !!!!!!"
      - name: Execute the testcases
        run: |
          make execute_test
          echo "#### Executing the test cases completed  !!!!!!"
          echo ${{ github.ref_name }}
      - name: Adding test executable in zip format
        run: zip buffer_test.zip buffer_test.out
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: buffer_test
          prerelease: true
          title: Latest Buffer test Binary
          files: buffer_test.zip